### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined in a RadListView

### ISSUE THREAD

**Issue by shiv19** [NativeScript/ns-v8ios-runtime#18]
Here's the log

```
CONSOLE ERROR: {
"context": "__onDiscardedError",
"keys": "stackTrace"
}
CONSOLE ERROR: Error Domain=undefined@undefined:undefined Code=-6661 "(null)" UserInfo={msg=TypeError: Cannot read property 'toLowerCase' of undefined, stackTrace=        (file:///node_modules/nativescript-ui-listview/ui-listview.js:1680:0)
at (file:///node_modules/nativescript-ui-listview/ui-listview.js:627:0)
at (file:///app/shared/helpers/converters.js:57:10)
at (file:///node_modules/@nativescript/core/ui/core/view/view.js:167:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view.js:68:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-helper/view-helper-common.js:99:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-common.js:860:0)
at (file:///node_modules/@nativescript/core/ui/layouts/grid-layout/grid-layout.js:167:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view.js:76:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-helper/view-helper-common.js:99:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-common.js:860:0)
at (file:///node_modules/@nativescript/core/ui/layouts/grid-layout/grid-layout.js:167:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view.js:76:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-helper/view-helper-common.js:99:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-common.js:860:0)
at (file:///node_modules/@nativescript/core/ui/layouts/grid-layout/grid-layout.js:167:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view.js:76:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-helper/view-helper-common.js:99:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-common.js:860:0)
at (file:///node_modules/@nativescript/core/ui/layouts/grid-layout/grid-layout.js:167:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view.js:76:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-helper/view-helper-common.js:99:0)
at (file:///node_modules/@nativescript/core/ui/core/view/view-common.js:860:0)
a<\M-b\M^@\M-&>
NativeScript discarding uncaught JS exception!
CONSOLE ERROR: {
"context": "__onDiscardedError",
"keys": "stackTrace"
}
CONSOLE ERROR: Error Domain=undefined@undefined:undefined Code=-6661 "(null)" UserInfo={msg=TypeError: Cannot read property 'toLowerCase' of undefined, stackTrace=        (file:///node_modules/nativescript-ui-listview/ui-listview.js:1680:0)
at (file:///node_modules/nativescript-ui-listview/ui-listview.js:627:0)
}
NativeScript discarding uncaught JS exception!
*** Assertion failure in -[TKCollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3900.12.16/UICollectionView.m:2270
```

This page has a RadListView that has grouping enabled. It also has 4 item templates with unique keys.
RadListView without grouping is working fine.

**Comment by darind** [comment]
@shiv19, thanks for submitting this issue. Could you please try re-adding the `ios@beta-v8` platform and see if the published fix works for you?

**Comment by shiv19** [comment]
@darind I'm travelling today. I'll be able to test it tomorrow :)
Will report back asap

**Comment by shiv19** [comment]
@darind 
That worked :)
Pages with grouped rad list view is now loading fine.

the next hurdle is this

```
Successfully synced application gfconnect on device 995B4769-E03D-41E1-BFE4-7C6A4AE2C923.
CONSOLE LOG: Enabling Central Preservation
CONSOLE ERROR: {
"context": "__onDiscardedError",
"keys": "stackTrace"
}
CONSOLE ERROR: Error Domain=undefined@undefined:undefined Code=-6661 "(null)" UserInfo={msg=TypeError: Cannot read property 'count' of undefined, stackTrace=        (file:///node_modules/nativescript-couchbase-plugin/couchbase-plugin.js:574:0)
at getAll(file:///app/services/db-service.js:177:27)
at viewModel(file:///app/pages/equipment/brewEquipmentEdit-model.js:230:44)
at (file:///app/pages/equipment/brewEquipmentEdit-page.js:28:22)
at ./pages/equipment/brewEquipmentEdit-page.js(file:///app/bundle.js:13247:30)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at (file:///app/pages/sessions/session-detail/sessionDetail-page.js:1:0)
at ./pages/sessions/session-detail/sessionDetail-page.js(file:///app/bundle.js:31073:30)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at webpackContext(file:///app/\b_[\w-]*\.)scss)$:296:0)
at loader(file:///node_modules/@nativescript/core/globals/register-module-helpers.js:35:0)
at loadModule(file:///node_modules/@nativescript/core/globals/register-module-helpers.js:76:0)
at (file:///node_modules/@nativescript/core/ui/builder/builder.js:27:0)
at (file:///node_modules/@nativescript/core/ui/frame/frame-common.js:164:0)
at onSessionTap(file:///app/pages/sessions/sessions-view-model.js:167:29)
at invokeFunc(file:///node_modules/lodash/debounce.js:95:0<…>
NativeScript discarding uncaught JS exception!
```

**Comment by darind** [comment]
thanks, could you please provide some steps or sample code to reproduce this new issue?

**Comment by shiv19** [comment]
Will provide tomorrow. I didn't get much time to check it as I'm traveling

**Comment by darind** [comment]
I managed to find the issue. Will provide a fix soon.

**Comment by darind** [comment]
We have just released a fix for this. Please let me know if you encounter some other issues.

**Comment by shiv19** [comment]
It no longer crashes at the page where it crashed previously.
But I still see this in the log

```
CONSOLE ERROR: {
"context": "__onDiscardedError",
"keys": "stackTrace"
}
CONSOLE ERROR: Error Domain=undefined@undefined:undefined Code=-6661 "(null)" UserInfo={msg=TypeError: Cannot read property 'count' of undefined, stackTrace=(file:///node_modules/nativescript-couchbase-plugin/couchbase-plugin.js:574:0)
at getBrewsList(file:///app/services/brews-service.js:438:34)
at loadFunc(file:///app/pages/sessions/sessions-view-model.js:63:51)
at loadSessions(file:///app/pages/sessions/sessions-view-model.js:109:13)
at (file:///app/pages/sessions/sessions-page.js:37:11)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:192:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:130:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:0)
at (file:///node_modules/rxjs/_esm5/internal/operators/distinctUntilChanged.js:55:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:0)
at (file:///node_modules/rxjs/_esm5/internal/Subject.js:47:0)
at (file:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:38:0)
at syncBrews(file:///app/services/brews-service.js:389:24)
}
NativeScript discarding uncaught JS exception!
CONSOLE ERROR: {
"context": "__onDiscardedError",
"keys": "stackTrace"
}
CONSOLE ERROR: Error Domain=undefined@undefined:undefined Code=-6661 "(null)" UserInfo={msg=TypeError: Cannot read property 'count' of undefined, stackTrace=(file:///node_modules/nativescript-couchbase-plugin/couchbase-plugin.js:574:0)
at getBrewsList(file:///app/services/brews-service.js:438:34)
at loadFunc(file:///app/pages/sessions/sessions-view-model.js:63:51)
at loadSessions(file:///app/pages/sessions/sessions-view-model.js:109:13)
at (file:///app/pages/sessions/sessions-page.js:37:11)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:192:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:130:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:0)
at (file:///node_modules/rxjs/_esm5/internal/operators/distinctUntilChanged.js:55:0)
at (file:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:0)
at (file:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:22:0)
at (file:///node_modules/rxjs/_esm5/internal/Observable.js:43:0)
at (file:///node_modules/rxjs/_esm5/internal/Subject.js:89:0)
at (file:///node_modules/rxjs/_esm5/internal/Observable.js:29:0)
at (file:///node_modules/rxjs/_esm5/internal/operators/distinctUntilChanged.js:13:0)
at (file:///node_modules/rxjs/_esm5/internal/Observable.js:24:0)
at (file:///node_modules/rxjs/_esm5/internal/operators/takeUntil.js:17:0)
at (file:///node_modules/rxjs/_esm5/internal/Observable.js:24:0)
at pageLoaded(file:///app/bundle.<…>
NativeScript discarding uncaught JS exception!
```

I'll close this issue now as the issue reported here as been fixed. I'll create a separate issue for the uncaught JS exception.
