### ISSUE TITLE
crash on NSData.getBytes

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#39]
I get a crash on [that](https://github.com/farfromrefug/nativescript-carto/blob/5bc8c18b38d0daadcd33061952a6e0482e40096d/src/utils/index.ios.ts#L170) line
```
====== Assertion failed ======
Native stack trace:
1          0x10726cc0b tns::Assert(bool, v8::Isolate*) + 119
2          0x10728fba8 tns::Interop::WriteValue(v8::Local<v8::Context>, tns::TypeEncoding const*, void*, v8::Local<v8::Value>) + 2552
3          0x10728f18a tns::Interop::SetFFIParams(v8::Local<v8::Context>, tns::TypeEncoding const*, tns::FFICall*, int, int, tns::V8Args&) + 110
4          0x10728ee13 tns::Interop::CallFunctionInternal(tns::MethodCall&) + 385
5          0x1071d88df tns::ArgConverter::Invoke(v8::Local<v8::Context>, objc_class*, v8::Local<v8::Object>, tns::V8Args&, tns::MethodMeta const*, bool) + 741
6          0x10723273e tns::MetadataBuilder::InvokeMethod(v8::Local<v8::Context>, tns::MethodMeta const*, v8::Local<v8::Object>, tns::V8Args&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) + 76
7          0x10723201f tns::MetadataBuilder::MethodCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 219
8          0x1073a25ac v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 620
9          0x1073a1a5c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 556
10         0x1073a10a3 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 259
11         0x107bdee19 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
JavaScript stack trace:
at module.exports.push.../../nativescript-carto/plugin/utils/index.js.NTDirAssetPackageImpl.loadAsset (file:///app/bundle.js:3264:18)
at module.exports.push.../../nativescript-carto/plugin/vectortiles/index.js.MBVectorTileDecoder.createNative (file:///app/bundle.js:4295:50)
at module.exports.push.../../nativescript-carto/plugin/index.common.js.BaseNative.getNative (file:///app/bundle.js:1047:32)
at module.exports.push.../../nativescript-carto/plugin/vectortiles/index.js.MBVectorTileDecoder.setStyleParameter (file:///app/bundle.js:4319:14)
at module.exports.push.../node_modules/string-replace-loader/index.js?!../node_modules/string-replace-loader/index.js?!../node_modules/ts-loader/index.js?!./components/Map.ts?vue&type=script&lang=ts&.Map.updateLanguage (file:///app/bundle.js:10640:17)
at module.exports.push.../node_modules/string-replace-loader/index.js?!../node_modules/string-replace-loader/index.js?!../node_modules/ts-loader/index.js?!./components/Map.ts?vue&type=script&lang=ts&.Map.setCurrentLaye<…>
```

Right now might not be easy to create a simple example. Let me know if the stack is not enough

**Comment by darind** [comment]
@farfromrefug, we have released a fix. Could you try it in your app?

**Comment by farfromrefug** [comment]
@darind seems to be fixed. I ll close this and come back if i still see the issue
